### ISSUE TITLE
ip and domain data, no: private

### ISSUE THREAD

**Issue by catbreast** [foreversam/xray-magisk#1]
https://github.com/Loyalsoldier/v2ray-rules-dat

use this。

**Comment by foreversam** [comment]
I think both of them have the `geoip:private` and `geosite:private`.
[v2fly/geoip](https://github.com/v2fly/geoip): [main.go](https://github.com/v2fly/geoip/blob/master/main.go#L31)
[v2fly/domain-list-community](https://github.com/v2fly/domain-list-community): [private](https://github.com/v2fly/domain-list-community/blob/master/data/private)
[Loyalsoldier/geoip](https://github.com/Loyalsoldier/geoip): [private](https://github.com/Loyalsoldier/geoip/blob/master/data/private)
[Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom): [private.txt](https://github.com/Loyalsoldier/domain-list-custom/blob/release/private.txt)

Users can download their favorite geo data at any time. Actually I have used [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) for a long time, but I would like to set geo data from V2Fly as default. 😀
